### ISSUE TITLE
minor quibble

### ISSUE THREAD

**Issue by dkebler** [synapticism/sass-font-stacker#1]
using an underscore in  font_stacker.scss is unconventional to every other bower package I have and is inconsistent to using - in your folder name.  I could just change it but when I do bower update there will be issues.  :-).

**Comment by xsynaptic** [comment]
Hmm! I never noticed that before but you're right. Fixed; latest ver should take care of this, let me know if it doesn't.

**Comment by dkebler** [comment]
BTW thanks for the time you have invested.  Made knowing which stacks are
"ok" easy.

On Thu, Feb 5, 2015 at 12:08 PM, Alexander Synaptic <
notifications@github.com> wrote:

> Closed #1 https://github.com/synapticism/sass-font-stacker/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/synapticism/sass-font-stacker/issues/1#event-231025722
> .

## 

Cheers, Cuidate, TTFN http://www.youtube.com/watch?v=5Gu50vq5ux4
David

**Comment by xsynaptic** [comment]
Hey, no problem. I'm glad it's useful :)
